In [28]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
%matplotlib inline

In [29]:
data = pd.read_csv('arrhythmia_csv.csv')

In [ ]:
data.info()

In [ ]:
data.describe()

In [ ]:
#missing values
impute = KNNImputer(n_neighbors = 2)
data = pd.DataFrame(impute.fit_transform(data), columns=data.columns)
data

In [ ]:
sns.countplot(x = 'class', data = data)

## stndard variables

In [ ]:
scaler = StandardScaler()
scaled_features = scaler.fit_transform(data.drop('class', axis= 1))
scaled_features

In [ ]:
normal_data = pd.DataFrame(scaled_features, columns=data.columns[:-1])
normal_data

In [ ]:
x_train, x_tets, y_train, y_test = train_test_split(normal_data, data['class'], test_size= 0.3 )

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
knn = KNeighborsClassifier(n_neighbors = 30, metric = 'euclidean')
knn.fit(x_train, y_train)
y_pred = knn.predict(x_tets)
y_pred_train = knn.predict(x_train)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix


In [31]:
print(confusion_matrix(y_test, y_pred))

[[82  0  0  0  0  0  0  0  0  0  0]
 [12  0  0  0  0  0  0  0  0  0  0]
 [ 5  0  0  0  0  0  0  0  0  0  0]
 [ 4  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0]
 [ 7  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0]
 [14  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0]
 [ 7  0  0  0  0  0  0  0  0  0  0]]


In [32]:
#train
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

[[163   0   0   0   0   0   0   0   0   0   0   0]
 [ 32   0   0   0   0   0   0   0   0   0   0   0]
 [ 10   0   0   0   0   0   0   0   0   0   0   0]
 [ 11   0   0   0   0   0   0   0   0   0   0   0]
 [ 12   0   0   0   0   0   0   0   0   0   0   0]
 [ 18   0   0   0   0   0   0   0   0   0   0   0]
 [  3   0   0   0   0   0   0   0   0   0   0   0]
 [  9   0   0   0   0   0   0   0   0   0   0   0]
 [ 35   0   0   0   0   0   0   0   1   0   0   0]
 [  3   0   0   0   0   0   0   0   0   0   0   0]
 [  4   0   0   0   0   0   0   0   0   0   0   0]
 [ 15   0   0   0   0   0   0   0   0   0   0   0]]
              precision    recall  f1-score   support

         1.0       0.52      1.00      0.68       163
         2.0       0.00      0.00      0.00        32
         3.0       0.00      0.00      0.00        10
         4.0       0.00      0.00      0.00        11
         5.0       0.00      0.00      0.00        12
         6.0       0.00      0.00      0.00        18
        

C:\Users\Hmdh\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [33]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         1.0       0.60      1.00      0.75        82
         2.0       0.00      0.00      0.00        12
         3.0       0.00      0.00      0.00         5
         4.0       0.00      0.00      0.00         4
         5.0       0.00      0.00      0.00         1
         6.0       0.00      0.00      0.00         7
         8.0       0.00      0.00      0.00         2
        10.0       0.00      0.00      0.00        14
        14.0       0.00      0.00      0.00         1
        15.0       0.00      0.00      0.00         1
        16.0       0.00      0.00      0.00         7

    accuracy                           0.60       136
   macro avg       0.05      0.09      0.07       136
weighted avg       0.36      0.60      0.45       136



## Gridsearch

In [ ]:
from sklearn.model_selection import GridSearchCV

In [34]:
param_grid = {'n_neighbors': list(range(1, 30)), 'metric': ['euclidean', 'manhattan', 'cosine']}

In [ ]:
# gs = GridSearchCV(KNeighborsClassifier(), param_grid, verbose = 1, cv = 5, n_jobs = -1, scoring = 'recall')

In [ ]:
# gs_result = gs.fit(x_train, y_train)

In [39]:
my_scorer = recall_score(y_test, y_pred, average='micro')
grid = GridSearchCV(knn, param_grid, verbose = 3, cv = 5, scoring = ['f1_macro', 'accuracy'], refit='accuracy' )

In [40]:
grid.fit(x_train, y_train)

Fitting 5 folds for each of 87 candidates, totalling 435 fits
[CV] metric=euclidean, n_neighbors=1 .................................
[CV]  metric=euclidean, n_neighbors=1, accuracy=0.422, f1_macro=0.167, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV]  metric=euclidean, n_neighbors=1, accuracy=0.603, f1_macro=0.372, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV]  metric=euclidean, n_neighbors=1, accuracy=0.540, f1_macro=0.254, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV]  metric=euclidean, n_neighbors=1, accuracy=0.524, f1_macro=0.341, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV]  metric=euclidean, n_neighbors=1, accuracy=0.571, f1_macro=0.333, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV]  metric=euclidean, n_neighbors=2, accuracy=0.531, f1_macro=0.160, total=   0.0s

C:\Users\Hmdh\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s



[CV] metric=euclidean, n_neighbors=2 .................................
[CV]  metric=euclidean, n_neighbors=2, accuracy=0.556, f1_macro=0.218, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV]  metric=euclidean, n_neighbors=2, accuracy=0.540, f1_macro=0.177, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV]  metric=euclidean, n_neighbors=2, accuracy=0.571, f1_macro=0.254, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV]  metric=euclidean, n_neighbors=2, accuracy=0.556, f1_macro=0.255, total=   0.0s
[CV] metric=euclidean, n_neighbors=3 .................................
[CV]  metric=euclidean, n_neighbors=3, accuracy=0.516, f1_macro=0.188, total=   0.0s
[CV] metric=euclidean, n_neighbors=3 .................................
[CV]  metric=euclidean, n_neighbors=3, accuracy=0.587, f1_macro=0.374, total=   0.0s
[CV] metric=euclidean, n_neighbors=3 ..........................

[CV]  metric=euclidean, n_neighbors=13, accuracy=0.540, f1_macro=0.109, total=   0.0s
[CV] metric=euclidean, n_neighbors=14 ................................
[CV]  metric=euclidean, n_neighbors=14, accuracy=0.531, f1_macro=0.085, total=   0.0s
[CV] metric=euclidean, n_neighbors=14 ................................
[CV]  metric=euclidean, n_neighbors=14, accuracy=0.524, f1_macro=0.063, total=   0.0s
[CV] metric=euclidean, n_neighbors=14 ................................
[CV]  metric=euclidean, n_neighbors=14, accuracy=0.540, f1_macro=0.083, total=   0.0s
[CV] metric=euclidean, n_neighbors=14 ................................
[CV]  metric=euclidean, n_neighbors=14, accuracy=0.508, f1_macro=0.061, total=   0.0s
[CV] metric=euclidean, n_neighbors=14 ................................
[CV]  metric=euclidean, n_neighbors=14, accuracy=0.540, f1_macro=0.111, total=   0.0s
[CV] metric=euclidean, n_neighbors=15 ................................
[CV]  metric=euclidean, n_neighbors=15, accuracy=0.531, f1

[CV]  metric=euclidean, n_neighbors=25, accuracy=0.524, f1_macro=0.063, total=   0.0s
[CV] metric=euclidean, n_neighbors=25 ................................
[CV]  metric=euclidean, n_neighbors=25, accuracy=0.508, f1_macro=0.061, total=   0.0s
[CV] metric=euclidean, n_neighbors=25 ................................
[CV]  metric=euclidean, n_neighbors=25, accuracy=0.524, f1_macro=0.085, total=   0.0s
[CV] metric=euclidean, n_neighbors=26 ................................
[CV]  metric=euclidean, n_neighbors=26, accuracy=0.516, f1_macro=0.062, total=   0.0s
[CV] metric=euclidean, n_neighbors=26 ................................
[CV]  metric=euclidean, n_neighbors=26, accuracy=0.524, f1_macro=0.063, total=   0.0s
[CV] metric=euclidean, n_neighbors=26 ................................
[CV]  metric=euclidean, n_neighbors=26, accuracy=0.524, f1_macro=0.063, total=   0.0s
[CV] metric=euclidean, n_neighbors=26 ................................
[CV]  metric=euclidean, n_neighbors=26, accuracy=0.508, f1

[CV]  metric=manhattan, n_neighbors=6, accuracy=0.587, f1_macro=0.224, total=   0.0s
[CV] metric=manhattan, n_neighbors=7 .................................
[CV]  metric=manhattan, n_neighbors=7, accuracy=0.547, f1_macro=0.146, total=   0.0s
[CV] metric=manhattan, n_neighbors=7 .................................
[CV]  metric=manhattan, n_neighbors=7, accuracy=0.571, f1_macro=0.191, total=   0.0s
[CV] metric=manhattan, n_neighbors=7 .................................
[CV]  metric=manhattan, n_neighbors=7, accuracy=0.571, f1_macro=0.206, total=   0.0s
[CV] metric=manhattan, n_neighbors=7 .................................
[CV]  metric=manhattan, n_neighbors=7, accuracy=0.540, f1_macro=0.204, total=   0.0s
[CV] metric=manhattan, n_neighbors=7 .................................
[CV]  metric=manhattan, n_neighbors=7, accuracy=0.587, f1_macro=0.224, total=   0.0s
[CV] metric=manhattan, n_neighbors=8 .................................
[CV]  metric=manhattan, n_neighbors=8, accuracy=0.578, f1_macro=

[CV]  metric=manhattan, n_neighbors=18, accuracy=0.516, f1_macro=0.062, total=   0.0s
[CV] metric=manhattan, n_neighbors=18 ................................
[CV]  metric=manhattan, n_neighbors=18, accuracy=0.524, f1_macro=0.063, total=   0.0s
[CV] metric=manhattan, n_neighbors=18 ................................
[CV]  metric=manhattan, n_neighbors=18, accuracy=0.524, f1_macro=0.063, total=   0.0s
[CV] metric=manhattan, n_neighbors=18 ................................
[CV]  metric=manhattan, n_neighbors=18, accuracy=0.508, f1_macro=0.061, total=   0.0s
[CV] metric=manhattan, n_neighbors=18 ................................
[CV]  metric=manhattan, n_neighbors=18, accuracy=0.524, f1_macro=0.085, total=   0.0s
[CV] metric=manhattan, n_neighbors=19 ................................
[CV]  metric=manhattan, n_neighbors=19, accuracy=0.516, f1_macro=0.062, total=   0.0s
[CV] metric=manhattan, n_neighbors=19 ................................
[CV]  metric=manhattan, n_neighbors=19, accuracy=0.524, f1

[CV]  metric=cosine, n_neighbors=1, accuracy=0.375, f1_macro=0.211, total=   0.0s
[CV] metric=cosine, n_neighbors=1 ....................................
[CV]  metric=cosine, n_neighbors=1, accuracy=0.571, f1_macro=0.463, total=   0.0s
[CV] metric=cosine, n_neighbors=1 ....................................
[CV]  metric=cosine, n_neighbors=1, accuracy=0.587, f1_macro=0.347, total=   0.0s
[CV] metric=cosine, n_neighbors=1 ....................................
[CV]  metric=cosine, n_neighbors=1, accuracy=0.603, f1_macro=0.422, total=   0.0s
[CV] metric=cosine, n_neighbors=1 ....................................
[CV]  metric=cosine, n_neighbors=1, accuracy=0.556, f1_macro=0.479, total=   0.0s
[CV] metric=cosine, n_neighbors=2 ....................................
[CV]  metric=cosine, n_neighbors=2, accuracy=0.484, f1_macro=0.228, total=   0.0s
[CV] metric=cosine, n_neighbors=2 ....................................
[CV]  metric=cosine, n_neighbors=2, accuracy=0.635, f1_macro=0.348, total=   0.0s


[CV]  metric=cosine, n_neighbors=11, accuracy=0.571, f1_macro=0.241, total=   0.0s
[CV] metric=cosine, n_neighbors=12 ...................................
[CV]  metric=cosine, n_neighbors=12, accuracy=0.609, f1_macro=0.321, total=   0.0s
[CV] metric=cosine, n_neighbors=12 ...................................
[CV]  metric=cosine, n_neighbors=12, accuracy=0.635, f1_macro=0.354, total=   0.0s
[CV] metric=cosine, n_neighbors=12 ...................................
[CV]  metric=cosine, n_neighbors=12, accuracy=0.635, f1_macro=0.289, total=   0.0s
[CV] metric=cosine, n_neighbors=12 ...................................
[CV]  metric=cosine, n_neighbors=12, accuracy=0.651, f1_macro=0.404, total=   0.0s
[CV] metric=cosine, n_neighbors=12 ...................................
[CV]  metric=cosine, n_neighbors=12, accuracy=0.556, f1_macro=0.195, total=   0.0s
[CV] metric=cosine, n_neighbors=13 ...................................
[CV]  metric=cosine, n_neighbors=13, accuracy=0.609, f1_macro=0.321, total= 

[CV]  metric=cosine, n_neighbors=24, accuracy=0.587, f1_macro=0.293, total=   0.0s
[CV] metric=cosine, n_neighbors=24 ...................................
[CV]  metric=cosine, n_neighbors=24, accuracy=0.556, f1_macro=0.185, total=   0.0s
[CV] metric=cosine, n_neighbors=25 ...................................
[CV]  metric=cosine, n_neighbors=25, accuracy=0.594, f1_macro=0.207, total=   0.0s
[CV] metric=cosine, n_neighbors=25 ...................................
[CV]  metric=cosine, n_neighbors=25, accuracy=0.571, f1_macro=0.258, total=   0.0s
[CV] metric=cosine, n_neighbors=25 ...................................
[CV]  metric=cosine, n_neighbors=25, accuracy=0.587, f1_macro=0.183, total=   0.0s
[CV] metric=cosine, n_neighbors=25 ...................................
[CV]  metric=cosine, n_neighbors=25, accuracy=0.571, f1_macro=0.231, total=   0.0s
[CV] metric=cosine, n_neighbors=25 ...................................
[CV]  metric=cosine, n_neighbors=25, accuracy=0.540, f1_macro=0.164, total= 

[Parallel(n_jobs=1)]: Done 435 out of 435 | elapsed:    9.1s finished


GridSearchCV(cv=5, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='euclidean',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=30, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'metric': ['euclidean', 'manhattan', 'cosine'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29]},
             pre_dispatch='2*n_jobs', refit='accuracy',
             return_train_score=False, scoring=['f1_macro', 'accuracy'],
             verbose=3)

In [41]:
grid.best_params_

{'metric': 'cosine', 'n_neighbors': 10}

In [42]:
grid.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='cosine',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [43]:
grid_prediction = grid.predict(x_tets)

In [44]:
print(confusion_matrix(y_test, grid_prediction))

[[79  2  0  0  0  0  0  0  1  0  0  0]
 [10  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  5  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  3  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0]
 [ 7  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 9  0  0  0  0  0  0  0  5  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0]
 [ 5  1  0  0  0  0  0  1  0  0  0  0]]


In [45]:
print(classification_report(y_test, grid_prediction))

              precision    recall  f1-score   support

         1.0       0.68      0.96      0.80        82
         2.0       0.40      0.17      0.24        12
         3.0       1.00      1.00      1.00         5
         4.0       1.00      0.75      0.86         4
         5.0       0.00      0.00      0.00         1
         6.0       0.00      0.00      0.00         7
         8.0       0.00      0.00      0.00         2
         9.0       0.00      0.00      0.00         0
        10.0       0.83      0.36      0.50        14
        14.0       0.00      0.00      0.00         1
        15.0       0.00      0.00      0.00         1
        16.0       0.00      0.00      0.00         7

    accuracy                           0.69       136
   macro avg       0.33      0.27      0.28       136
weighted avg       0.60      0.69      0.62       136



C:\Users\Hmdh\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Hmdh\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [47]:
grid = GridSearchCV(knn, param_grid, verbose = 3, cv = 5, scoring = ['f1_macro', 'accuracy'], refit='f1_macro' )

In [48]:
grid.fit(x_train, y_train)

Fitting 5 folds for each of 87 candidates, totalling 435 fits
[CV] metric=euclidean, n_neighbors=1 .................................
[CV]  metric=euclidean, n_neighbors=1, accuracy=0.422, f1_macro=0.167, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV]  metric=euclidean, n_neighbors=1, accuracy=0.603, f1_macro=0.372, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV]  metric=euclidean, n_neighbors=1, accuracy=0.540, f1_macro=0.254, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV]  metric=euclidean, n_neighbors=1, accuracy=0.524, f1_macro=0.341, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV]  metric=euclidean, n_neighbors=1, accuracy=0.571, f1_macro=0.333, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV]  metric=euclidean, n_neighbors=2, accuracy=0.531, f1_macro=0.160, total=   0.0s
[C

C:\Users\Hmdh\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV]  metric=euclidean, n_neighbors=2, accuracy=0.540, f1_macro=0.177, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV]  metric=euclidean, n_neighbors=2, accuracy=0.571, f1_macro=0.254, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV]  metric=euclidean, n_neighbors=2, accuracy=0.556, f1_macro=0.255, total=   0.0s
[CV] metric=euclidean, n_neighbors=3 .................................
[CV]  metric=euclidean, n_neighbors=3, accuracy=0.516, f1_macro=0.188, total=   0.0s
[CV] metric=euclidean, n_neighbors=3 .................................
[CV]  metric=euclidean, n_neighbors=3, accuracy=0.587, f1_macro=0.374, total=   0.0s
[CV] metric=euclidean, n_neighbors=3 .................................
[CV]  metric=euclidean, n_neighbors=3, accuracy=0.571, f1_macro=0.217, total=   0.0s
[CV] metric=euclidean, n_neighbors=3 .................................
[CV]  metric=euclidean, n_neighbors=3, accuracy=0.556, f1_macro=

[CV]  metric=euclidean, n_neighbors=13, accuracy=0.508, f1_macro=0.061, total=   0.0s
[CV] metric=euclidean, n_neighbors=13 ................................
[CV]  metric=euclidean, n_neighbors=13, accuracy=0.540, f1_macro=0.109, total=   0.0s
[CV] metric=euclidean, n_neighbors=14 ................................
[CV]  metric=euclidean, n_neighbors=14, accuracy=0.531, f1_macro=0.085, total=   0.0s
[CV] metric=euclidean, n_neighbors=14 ................................
[CV]  metric=euclidean, n_neighbors=14, accuracy=0.524, f1_macro=0.063, total=   0.0s
[CV] metric=euclidean, n_neighbors=14 ................................
[CV]  metric=euclidean, n_neighbors=14, accuracy=0.540, f1_macro=0.083, total=   0.0s
[CV] metric=euclidean, n_neighbors=14 ................................
[CV]  metric=euclidean, n_neighbors=14, accuracy=0.508, f1_macro=0.061, total=   0.0s
[CV] metric=euclidean, n_neighbors=14 ................................
[CV]  metric=euclidean, n_neighbors=14, accuracy=0.540, f1

[CV]  metric=euclidean, n_neighbors=24, accuracy=0.524, f1_macro=0.085, total=   0.0s
[CV] metric=euclidean, n_neighbors=25 ................................
[CV]  metric=euclidean, n_neighbors=25, accuracy=0.516, f1_macro=0.062, total=   0.0s
[CV] metric=euclidean, n_neighbors=25 ................................
[CV]  metric=euclidean, n_neighbors=25, accuracy=0.524, f1_macro=0.063, total=   0.0s
[CV] metric=euclidean, n_neighbors=25 ................................
[CV]  metric=euclidean, n_neighbors=25, accuracy=0.524, f1_macro=0.063, total=   0.0s
[CV] metric=euclidean, n_neighbors=25 ................................
[CV]  metric=euclidean, n_neighbors=25, accuracy=0.508, f1_macro=0.061, total=   0.0s
[CV] metric=euclidean, n_neighbors=25 ................................
[CV]  metric=euclidean, n_neighbors=25, accuracy=0.524, f1_macro=0.085, total=   0.0s
[CV] metric=euclidean, n_neighbors=26 ................................
[CV]  metric=euclidean, n_neighbors=26, accuracy=0.516, f1

[CV]  metric=manhattan, n_neighbors=7, accuracy=0.587, f1_macro=0.224, total=   0.0s
[CV] metric=manhattan, n_neighbors=8 .................................
[CV]  metric=manhattan, n_neighbors=8, accuracy=0.578, f1_macro=0.231, total=   0.0s
[CV] metric=manhattan, n_neighbors=8 .................................
[CV]  metric=manhattan, n_neighbors=8, accuracy=0.540, f1_macro=0.124, total=   0.0s
[CV] metric=manhattan, n_neighbors=8 .................................
[CV]  metric=manhattan, n_neighbors=8, accuracy=0.556, f1_macro=0.155, total=   0.0s
[CV] metric=manhattan, n_neighbors=8 .................................
[CV]  metric=manhattan, n_neighbors=8, accuracy=0.556, f1_macro=0.208, total=   0.0s
[CV] metric=manhattan, n_neighbors=8 .................................
[CV]  metric=manhattan, n_neighbors=8, accuracy=0.556, f1_macro=0.170, total=   0.0s
[CV] metric=manhattan, n_neighbors=9 .................................
[CV]  metric=manhattan, n_neighbors=9, accuracy=0.547, f1_macro=

[CV]  metric=manhattan, n_neighbors=19, accuracy=0.508, f1_macro=0.061, total=   0.0s
[CV] metric=manhattan, n_neighbors=19 ................................
[CV]  metric=manhattan, n_neighbors=19, accuracy=0.524, f1_macro=0.085, total=   0.0s
[CV] metric=manhattan, n_neighbors=20 ................................
[CV]  metric=manhattan, n_neighbors=20, accuracy=0.516, f1_macro=0.062, total=   0.0s
[CV] metric=manhattan, n_neighbors=20 ................................
[CV]  metric=manhattan, n_neighbors=20, accuracy=0.524, f1_macro=0.063, total=   0.0s
[CV] metric=manhattan, n_neighbors=20 ................................
[CV]  metric=manhattan, n_neighbors=20, accuracy=0.524, f1_macro=0.063, total=   0.0s
[CV] metric=manhattan, n_neighbors=20 ................................
[CV]  metric=manhattan, n_neighbors=20, accuracy=0.508, f1_macro=0.061, total=   0.0s
[CV] metric=manhattan, n_neighbors=20 ................................
[CV]  metric=manhattan, n_neighbors=20, accuracy=0.508, f1

[CV]  metric=cosine, n_neighbors=2, accuracy=0.667, f1_macro=0.480, total=   0.0s
[CV] metric=cosine, n_neighbors=3 ....................................
[CV]  metric=cosine, n_neighbors=3, accuracy=0.516, f1_macro=0.259, total=   0.0s
[CV] metric=cosine, n_neighbors=3 ....................................
[CV]  metric=cosine, n_neighbors=3, accuracy=0.651, f1_macro=0.441, total=   0.0s
[CV] metric=cosine, n_neighbors=3 ....................................
[CV]  metric=cosine, n_neighbors=3, accuracy=0.619, f1_macro=0.345, total=   0.0s
[CV] metric=cosine, n_neighbors=3 ....................................
[CV]  metric=cosine, n_neighbors=3, accuracy=0.619, f1_macro=0.449, total=   0.0s
[CV] metric=cosine, n_neighbors=3 ....................................
[CV]  metric=cosine, n_neighbors=3, accuracy=0.746, f1_macro=0.581, total=   0.0s
[CV] metric=cosine, n_neighbors=4 ....................................
[CV]  metric=cosine, n_neighbors=4, accuracy=0.500, f1_macro=0.228, total=   0.0s


[CV]  metric=cosine, n_neighbors=16, accuracy=0.603, f1_macro=0.264, total=   0.0s
[CV] metric=cosine, n_neighbors=16 ...................................
[CV]  metric=cosine, n_neighbors=16, accuracy=0.667, f1_macro=0.423, total=   0.0s
[CV] metric=cosine, n_neighbors=16 ...................................
[CV]  metric=cosine, n_neighbors=16, accuracy=0.540, f1_macro=0.182, total=   0.0s
[CV] metric=cosine, n_neighbors=17 ...................................
[CV]  metric=cosine, n_neighbors=17, accuracy=0.609, f1_macro=0.321, total=   0.0s
[CV] metric=cosine, n_neighbors=17 ...................................
[CV]  metric=cosine, n_neighbors=17, accuracy=0.587, f1_macro=0.261, total=   0.0s
[CV] metric=cosine, n_neighbors=17 ...................................
[CV]  metric=cosine, n_neighbors=17, accuracy=0.603, f1_macro=0.264, total=   0.0s
[CV] metric=cosine, n_neighbors=17 ...................................
[CV]  metric=cosine, n_neighbors=17, accuracy=0.651, f1_macro=0.404, total= 

[CV]  metric=cosine, n_neighbors=29, accuracy=0.556, f1_macro=0.170, total=   0.0s
[CV] metric=cosine, n_neighbors=29 ...................................
[CV]  metric=cosine, n_neighbors=29, accuracy=0.524, f1_macro=0.102, total=   0.0s


[Parallel(n_jobs=1)]: Done 435 out of 435 | elapsed:    9.0s finished


GridSearchCV(cv=5, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='euclidean',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=30, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'metric': ['euclidean', 'manhattan', 'cosine'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29]},
             pre_dispatch='2*n_jobs', refit='f1_macro',
             return_train_score=False, scoring=['f1_macro', 'accuracy'],
             verbose=3)

In [49]:
grid.best_params_

{'metric': 'cosine', 'n_neighbors': 3}

In [50]:
grid.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='cosine',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [51]:
grid_prediction = grid.predict(x_tets)

In [52]:
print(confusion_matrix(y_test, grid_prediction))
print(classification_report(y_test, grid_prediction))

[[70  4  1  1  1  2  0  3  0  0  0]
 [ 8  3  1  0  0  0  0  0  0  0  0]
 [ 0  0  5  0  0  0  0  0  0  0  0]
 [ 1  0  0  3  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0]
 [ 7  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0]
 [ 8  1  0  0  0  0  0  5  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0]
 [ 5  1  0  0  0  1  0  0  0  0  0]]
              precision    recall  f1-score   support

         1.0       0.68      0.85      0.76        82
         2.0       0.33      0.25      0.29        12
         3.0       0.62      1.00      0.77         5
         4.0       0.75      0.75      0.75         4
         5.0       0.00      0.00      0.00         1
         6.0       0.00      0.00      0.00         7
         8.0       0.00      0.00      0.00         2
        10.0       0.62      0.36      0.45        14
        14.0       0.00      0.00      0.00         1
        15.0       0.00      0.00      0.00         1
        

C:\Users\Hmdh\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
